# Generated by Django 3.0.5 on 2021-04-11 10:16

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('passwordLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkaudioname',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Video'),
        ),
    ]
